#!/usr/bin/env python3
"""Run scenario evidence tests and regenerate the scenario scoreboard."""

from __future__ import annotations

import re
import os
import subprocess
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOC_PATH = ROOT / "docs/scenarios.md"


@dataclass(frozen=True)
class Scenario:
    number: str
    name: str
    slug: str
    test_path: str

    @property
    def report_path(self) -> Path:
        return ROOT / "examples/scenarios" / self.slug / "REPORT.md"


SCENARIOS = (
    Scenario("01", "MNI spotlight", "01_mni_spotlight", "examples/scenarios/test_s01_mni_spotlight.py"),
    Scenario("02", "ROI mean time series", "02_roi_mean_timeseries", "examples/scenarios/test_s02_roi_mean_timeseries.py"),
    Scenario("03", "Seed-sphere mean", "03_seed_sphere_mean", "examples/scenarios/test_s03_seed_sphere_mean.py"),
    Scenario("04", "Temporal SNR map", "04_temporal_snr_map", "examples/scenarios/test_s04_temporal_snr_map.py"),
    Scenario("05", "Receipt IO boundary", "05_receipt_io_boundary", "examples/scenarios/test_s05_receipt_io_boundary.py"),
)


def _section(text: str, heading: str) -> str:
    marker = f"## {heading}"
    start = text.find(marker)
    if start < 0:
        return ""
    start = text.find("\n", start)
    if start < 0:
        return ""
    next_heading = text.find("\n## ", start + 1)
    end = len(text) if next_heading < 0 else next_heading
    return text[start:end].strip()


def _first_bold_sentence(text: str, heading: str) -> str:
    section = _section(text, heading)
    match = re.search(r"\*\*(.+?)\*\*", section, flags=re.S)
    if not match:
        return "not reported"
    return " ".join(match.group(1).split())


def _headline_metric(text: str) -> str:
    scoreboard = _section(text, "Scoreboard")
    if "User-facing function body" in scoreboard:
        match = re.search(r"\| User-facing function body \|([^|\n]+)\|([^|\n]+)\|", scoreboard)
        if match:
            return f"body {match.group(1).strip()} -> {match.group(2).strip()}"
    if "Write derived map" in scoreboard:
        return "receipt survives write/read"
    return "see report"


def _run_scenario(scenario: Scenario) -> tuple[str, str]:
    pytest_cmd = os.environ.get("PYTEST", "pytest")
    cmd = [pytest_cmd, scenario.test_path, "-q"]
    proc = subprocess.run(cmd, cwd=ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    output = proc.stdout.strip().splitlines()
    summary = output[-1] if output else "no pytest output"
    status = "PASS" if proc.returncode == 0 else "FAIL"
    return status, summary


def _markdown(rows: list[dict[str, str]]) -> str:
    lines = [
        "# Scenario Evidence Scoreboard",
        "",
        "Generated by `make verify-evidence`. Each row runs the canonical scenario pytest and links back to the scenario report.",
        "",
        "| # | Scenario | Status | Pytest summary | Verdict | Headline metric | Report |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            "| {number} | {name} | {status} | `{summary}` | {verdict} | {metric} | [{slug}](../examples/scenarios/{slug}/REPORT.md) |".format(
                **row
            )
        )
    lines.extend(
        [
            "",
            "## Reproduce",
            "",
            "```bash",
            "make verify-evidence",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    rows: list[dict[str, str]] = []
    ok = True
    for scenario in SCENARIOS:
        report = scenario.report_path.read_text(encoding="utf-8")
        status, summary = _run_scenario(scenario)
        ok = ok and status == "PASS"
        rows.append(
            {
                "number": scenario.number,
                "name": scenario.name,
                "slug": scenario.slug,
                "status": status,
                "summary": summary,
                "verdict": _first_bold_sentence(report, "Verdict"),
                "metric": _headline_metric(report),
            }
        )

    print("| # | Scenario | Status | Pytest summary | Verdict | Headline metric |")
    print("|---|---|---|---|---|---|")
    for row in rows:
        print(
            "| {number} | {name} | {status} | {summary} | {verdict} | {metric} |".format(
                **row
            )
        )

    DOC_PATH.write_text(_markdown(rows), encoding="utf-8")
    print(f"\nWrote {DOC_PATH.relative_to(ROOT)}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
